Repository astral-sh/ruff-lsp, pull requests merged in 2024-02, with the labels that each got.

#374 Narrow Text edits
  ruff_lsp/server.py
  tests/test_format.py
Labels: enhancement

#380 Update ruff configuration to ruff 0.2
  pyproject.toml
  tests/conftest.py
Labels: internal

#385 Update Neovim documentation
  README.md
Labels: documentation

#393 Bump version to 0.0.53
  README.md
  requirements-dev.txt
  requirements.txt
  ruff_lsp/__init__.py
  tests/client/constants.py
  tests/client/defaults.py
  tests/client/utils.py
  tests/test_server.py
Labels: internal

#395 Refine release instructions
  README.md
Labels: internal

#391 Fixes #389, updating the readme for the helix configuration
  README.md
Labels: documentation
